In [2]:

import numpy as np # linear algebra
import pickle

In [8]:

# Load using the found path
ohe_sex = pickle.load(open('/kaggle/input/datasets/faizanhaider01/models/ohe_sex.pkl', 'rb'))
ohe_embarked = pickle.load(open('/kaggle/input/datasets/faizanhaider01/models/ohe_embarked.pkl', 'rb'))
clf = pickle.load(open('/kaggle/input/datasets/faizanhaider01/models/clf.pkl', 'rb'))

In [11]:
#pclass	/sex	/age	/sibsp	/parch	/fare	/embarked
test_input = np.array([2,'male',31.0,0,0,10.5,'S'],dtype=object).reshape(1,7)

In [12]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [13]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [14]:
test_input_sex #As male so 0,1 for female 1,0

array([[0., 1.]])

In [15]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [16]:
test_input_embarked

array([[0., 0., 1.]])

In [17]:
test_input_age = test_input[:,2].reshape(1,1)

In [18]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [19]:
test_input_transformed.shape

(1, 10)

In [21]:
test_input_transformed

array([[2, 0, 0, 10.5, 31.0, 0.0, 1.0, 0.0, 0.0, 1.0]], dtype=object)

In [22]:
clf.predict(test_input_transformed)

array([0])