In [136]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/datasets/faizanhaider01/study-grade-data/linear_regression_data.csv
/kaggle/input/datasets/faizanhaider01/health-dataset/health_risk_dataset.csv


In [137]:
class LR_mine:
    def __init__(self):
        self.m=None
        self.b=None
    def fit(self,x_train,y_train):
        num = 0
        den = 0
        for i in range(x_train.shape[0]):
            num = num + ((x_train[i]- x_train.mean())* (y_train[i]- y_train.mean()))
            den = den + ((x_train[i]- x_train.mean())* (x_train[i]- x_train.mean()))
        self.m = num/den
        self.b = y_train.mean() - (self.m * x_train.mean())
        print(f"The m value is {self.m}")
        print(f"The b value is {self.b}")
        
    def predict(self,x_test):
        print(x_test)
        return self.m * x_test + self.b
    

In [138]:
df = pd.read_csv('/kaggle/input/datasets/faizanhaider01/study-grade-data/linear_regression_data.csv')

In [139]:
df.head(5)

,study_hours,exam_score
0,1.2,52.3
1,2.5,61.8
2,0.8,48.7
3,3.1,68.4
4,4.0,75.2


In [140]:
x=df.iloc[:,0].values
y=df.iloc[:,1].values

In [141]:
x

array([1.2, 2.5, 0.8, 3.1, 4. , 2.2, 5.3, 1.5, 3.8, 6.1, 0.5, 4.7, 2.9,
       1. , 5.8, 3.5, 2. , 6.5, 1.8, 4.3, 0.3, 5. , 3.3, 2.7, 6.8, 1.3,
       4.5, 2.4, 0.9, 5.5, 3.7, 2.1, 6.2, 1.6, 4.1, 0.7, 5.7, 3.4, 2.8,
       6.6, 1.1, 4.8, 2.3, 1.4, 5.2, 3.6, 2.6, 6.9, 1.7, 4.4, 0.4, 5.4,
       3.2, 2.5, 6.3, 1.9, 4.6, 0.6, 5.6, 3.9, 2. , 6.7, 1.2, 4.2, 2.3,
       0.8, 5.1, 3.5, 2.9, 6.4, 1.5, 4.9, 3. , 1. , 5.9, 3.7, 2.2, 6.1,
       1.8, 4.3, 0.5, 5.3, 3.4, 2.7, 6.8, 1.3, 4.5, 2.4, 0.9, 5.5, 3.8,
       2.1, 6.2, 1.6, 4. , 0.7, 5.7, 3.3, 2.8, 6.6, 1.1, 4.8, 2.3, 1.4,
       5.2, 3.6, 2.6, 6.9, 1.7, 4.4, 0.4, 5.4, 3.2, 2.5, 6.3, 1.9, 4.6,
       0.6, 5.6, 3.9, 2. , 6.7, 1.2, 4.2, 2.3, 0.8, 5.1, 3.5, 2.9, 6.4,
       1.5, 4.9, 3. , 1. , 5.9, 3.7, 2.2, 6.1, 1.8, 4.3, 0.5, 5.3, 3.4,
       2.7, 6.8, 1.3, 4.5, 2.4, 0.9, 5.5, 3.8, 2.1, 6.2, 1.6, 4. , 0.7,
       5.7, 3.3, 2.8, 6.6, 1.1, 4.8, 2.3, 1.4, 5.2, 3.6, 2.6, 6.9, 1.7,
       4.4, 0.4, 5.4, 3.2, 2.5, 6.3, 1.9, 4.6, 0.6, 5.6, 3.9, 2.

In [142]:
y

array([52.3, 61.8, 48.7, 68.4, 75.2, 59.6, 84.1, 54.9, 73.5, 91.2, 46.3,
       79.8, 66.7, 50.1, 88.4, 71.3, 58.2, 93.7, 56.4, 77.6, 44.8, 82.3,
       69.5, 64.1, 96.2, 52.8, 78.9, 61.3, 49.4, 86.7, 72.8, 59. , 92.4,
       55.6, 76.3, 47.9, 87.8, 70.5, 65.3, 94.8, 51.4, 80.7, 60.5, 53.7,
       83.6, 72.1, 63.4, 97.5, 56.2, 78.1, 45.6, 85.4, 68.9, 62.7, 93.1,
       57.5, 79.4, 47.1, 87.1, 74.3, 58.8, 95.6, 52. , 77. , 60.9, 48.2,
       83. , 71.7, 65.9, 92.8, 54.4, 81.5, 67.3, 50.7, 89.2, 73.2, 59.8,
       91.7, 57. , 78.4, 46.8, 84.7, 70.9, 64.6, 96.9, 53.1, 79.3, 62.2,
       49.9, 87.3, 74. , 59.4, 92.1, 55.9, 76.8, 48.5, 88.1, 69.8, 65.7,
       95.3, 51.8, 81.1, 61.6, 54. , 84.2, 72.6, 63.9, 97.1, 56.7, 78.6,
       46.1, 85.9, 69.3, 63.2, 93.5, 58. , 79.9, 47.6, 87.5, 74.8, 59.3,
       96. , 52.5, 77.5, 61.2, 48.9, 83.5, 72.2, 66.4, 93.2, 54.7, 82. ,
       67.8, 51.2, 89.7, 73.7, 60.3, 92. , 57.4, 78.9, 47.3, 85.2, 71.4,
       65.1, 97.4, 53.5, 79.8, 62.7, 50.4, 87.8, 74

In [143]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [144]:
x_train.shape

(168,)

In [145]:
x_train.shape[0]

168

In [146]:
lr = LR_mine()

In [147]:
lr.fit(x_train,y_train)

The m value is 7.960207366565085
The b value is 43.239277302834196


In [148]:
x_test

array([4.9, 4.3, 0.5, 0.8, 3.3, 4. , 1.9, 4.2, 3.4, 1. , 1.3, 1.2, 3.7,
       2.1, 6.3, 2.7, 4.4, 4.8, 5.2, 6.4, 6.8, 4.9, 1.5, 1.9, 1.8, 6.8,
       5.1, 2.4, 5.5, 5.3, 0.9, 2.9, 5.5, 1.8, 0.7, 2.2, 1.7, 0.8, 1.5,
       3.1, 2.8, 5.8, 0.5])

In [151]:
x_test[0]

np.float64(4.9)

In [152]:
lr.predict(x_test[0])

4.9


np.float64(82.24429339900311)